name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Only trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout --orphan gh-pages
          git reset
          mv dist/* .
          rm -rf dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages